name: Tests

on: [push]

jobs:
  os-python-matrix:
    strategy:
      matrix:
        os:
          # Does not work
          # - name: macos
          #   icon: 🍏
          - name: ubuntu
            icon: 🐧
        python-version:
          - "3.12"
          # Does not work currently:
          # - "3.13"
          # - "3.14"

    runs-on: ${{ matrix.os.name }}-latest
    name: ${{ matrix.os.icon }} Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install macOS specific dependencies
        if: runner.os == 'macOS'
        run: brew install bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: ./bin/run_tests.sh
